config/routes.rb
Iconference::Application.routes.draw do
  
  resources :maps

  root :to => 'static_pages#home'
  
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contact',    to: 'static_pages#contact',    via: 'get'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      resources :conferences do
        resources :sessions, :presentations, :authors, :speakers, :events, :maps
        resources :sessions do
          :presentations
        end
      end

      match '/authenticate', to: 'access#create'
    end
  end

  

  namespace :admin, defaults: {format: 'html'} do
    match '/dashboard', :to => 'dashboard#menu', via: 'get'
    resources :access, only: [:new, :create, :destroy]
    resources :institutions, :org_members, :attendees
    match '/signin',  to: 'access#new'
    match '/signout', to: 'access#destroy', via: 'delete'

    resources :conferences do
      resources :sessions, :authors, :speakers, :events,
                :attendees, :maps
      resources :sessions do
        :presentations
      end
      member do
        post 'import'
      end
    end
  end

  resources :users, :attendees, :authors, :events, :coffee_breaks,
  :events, :institutions, :keynotes,
  :org_members, :presentations, :rooms,
  :sessions, :speakers, :welcome_sessions, :workshops, :maps

  resources :schedules do
    collection do
      put 'add'
      delete 'remove'
    end
  end

  resources :conferences do
    get 'program', :on => :member
    resources :events, :sessions, :presentations, :authors, :speakers, :maps
    end

  resources :presentations do
    resources :authors, :speakers
  end

  resources :sessions do
    resources :presentations
  end

=begin
  resources :schedules do
    resources :sessions do
      get 'delete', :on => :collection
    end
  end
=end
  

  match ':controller/:id/:action'
  match ':controller/:id/:action/:presentation_id'
  match ':controller(/:action(/:id))(.:format)'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :conference_id, :end_at, :local, :notes, :start_at, :title

  belongs_to :conference
  belongs_to :speaker
  has_and_belongs_to_many :schedules

  #Validations
  #validates :local, :presence => true
  #validates :end_at, :presence => true
  #validates :start_at, :presence => true
  #validates :title, :presence => true, :uniqueness => true

  def duration
    dur = (end_at - start_at) / 60
    dur.to_s
  end

end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController
    # GET /events
    # GET /events.json
    def index
      @conference = Conference.find(params[:conference_id])
      @events = @conference.events
    end

    # GET /events/1
    # GET /events/1.json
    def show
      @event = Event.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @event }
      end
    end

    # GET /events/new
    # GET /events/new.json
    def new
      @event = Event.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @event }
      end
    end

    # GET /events/1/edit
    def edit
      @event = Event.find(params[:id])
    end

    # POST /events
    # POST /events.json
    def create

      if (params[:conference_id] != nil)
        # conference = Conference.find(params[:conference_id])
        # presentations = params[:presentations]
        # presentations.each do |presentation|
        #   schedule.presentations << Presentation.find(presentation[:id])
        # end
        # render :nothing => true
      else

        @event = Event.new(params[:event])

        respond_to do |format|
          if @event.save
            format.html { redirect_to @event, notice: 'Event was successfully created.' }
            format.json { render json: @event, status: :created, location: @event }
          else
            format.html { render action: "new" }
            format.json { render json: @event.errors, status: :unprocessable_entity }
          end
        end
      end
    end

    # PUT /events/1
    # PUT /events/1.json
    def update
      @event = Event.find(params[:id])

      respond_to do |format|
        if @event.update_attributes(params[:event])
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event = Event.find(params[:id])
      @event.destroy

      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/api/v1/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create

    if (params[:conference_id] != nil)
     # conference = Conference.find(params[:conference_id])
     # presentations = params[:presentations]
     # presentations.each do |presentation|
     #   schedule.presentations << Presentation.find(presentation[:id])
     # end
     # render :nothing => true
    else

      @event = Event.new(params[:event])

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render json: @event, status: :created, location: @event }
        else
          format.html { render action: "new" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @conference =  Conference.find(params[:conference_id])
    @events = @conference.events

    respond_to do |format|
      format.html # index.html.erb
      format.json { render 'events/index'}
    end


  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create

    if (params[:conference_id] != nil)
     # conference = Conference.find(params[:conference_id])
     # presentations = params[:presentations]
     # presentations.each do |presentation|
     #   schedule.presentations << Presentation.find(presentation[:id])
     # end
     # render :nothing => true
    else

      @event = Event.new(params[:event])

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render json: @event, status: :created, location: @event }
        else
          format.html { render action: "new" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
	<div class="controls">
	  <%= f.label :type %><br />
	  <select id="selectError">
		<option>Welcome Session</option>
		<option>Keynote</option>
		<option>Workshop</option>
		<option>Coffee Break</option>
	  </select>
	</div>
	<div>
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.datetime_select :end_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/admin/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Local</th>
    <th>Type</th>
    <th>Start</th>
    <th>End</th>
	<th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.local %></td>
    <td><%= event.type %></td>
    <td><%= event.start_at %></td>
    <td><%= event.end_at %></td>
	<td><%= event.notes %></td>
    <td><%= link_to 'Show', admin_conference_event_url(@conference, event) %></td>
    <td><%= link_to 'Edit', edit_admin_conference_event_url(@conference, event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_admin_conference_event_path %> <br/>
<%= link_to 'Back', admin_conference_url(params[:conference_id]) %>

app/views/admin/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_conference_events_url(params[:conference_id]) %>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Conference:</b>
  <%= @event.conference_id %>
</p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Local:</b>
  <%= @event.local %>
</p>

<p>
  <b>Notes:</b>
  <%= @event.notes %>
</p>

<p>
  <b>Start:</b>
  <%= @event.start_at %>
</p>

<p>
  <b>End:</b>
  <%= @event.end_at %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>