config/routes.rb
Iconference::Application.routes.draw do
  
  resources :maps

  root :to => 'static_pages#home'
  
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contact',    to: 'static_pages#contact',    via: 'get'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      resources :conferences do
        resources :sessions, :presentations, :authors, :speakers, :events, :maps
        resources :sessions do
          :presentations
        end
      end

      match '/authenticate', to: 'access#create'
    end
  end

  

  namespace :admin, defaults: {format: 'html'} do
    match '/dashboard', :to => 'dashboard#menu', via: 'get'
    resources :access, only: [:new, :create, :destroy]
    resources :institutions, :org_members, :attendees
    match '/signin',  to: 'access#new'
    match '/signout', to: 'access#destroy', via: 'delete'

    resources :conferences do
      resources :sessions, :authors, :speakers, :events,
                :attendees, :maps
      resources :sessions do
        :presentations
      end
      member do
        post 'import'
      end
    end
  end

  resources :users, :attendees, :authors, :events, :coffee_breaks,
  :events, :institutions, :keynotes,
  :org_members, :presentations, :rooms,
  :sessions, :speakers, :welcome_sessions, :workshops, :maps

  resources :schedules do
    collection do
      put 'add'
      delete 'remove'
    end
  end

  resources :conferences do
    get 'program', :on => :member
    resources :events, :sessions, :presentations, :authors, :speakers, :maps
    end

  resources :presentations do
    resources :authors, :speakers
  end

  resources :sessions do
    resources :presentations
  end

=begin
  resources :schedules do
    resources :sessions do
      get 'delete', :on => :collection
    end
  end
=end
  

  match ':controller/:id/:action'
  match ':controller/:id/:action/:presentation_id'
  match ':controller(/:action(/:id))(.:format)'

end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :name, :map  , :remote_map_url

  has_and_belongs_to_many :conferences, :join_table => 'conferences_maps'

  mount_uploader :map, MapUploader
end

app/controllers/admin/maps_controller.rb
module Admin
  class MapsController < ApplicationController
    # GET /maps
    # GET /maps.json
    def index
      @conference = Conference.find(params[:conference_id])
      @maps = @conference.maps
    end

    # GET /maps/1
    # GET /maps/1.json
    def show
      @map = Map.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @map }
      end
    end

    # GET /maps/new
    # GET /maps/new.json
    def new
      @map = Map.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @map }
      end
    end

    # GET /maps/1/edit
    def edit
      @map = Map.find(params[:id])
    end

    # POST /maps
    # POST /maps.json
    def create
      @map = Map.new(params[:map])

      respond_to do |format|
        if @map.save
          format.html { redirect_to @map, notice: 'Map was successfully created.' }
          format.json { render json: @map, status: :created, location: @map }
        else
          format.html { render action: "new" }
          format.json { render json: @map.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /maps/1
    # PUT /maps/1.json
    def update
      @map = Map.find(params[:id])

      respond_to do |format|
        if @map.update_attributes(params[:map])
          format.html { redirect_to @map, notice: 'Map was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @map.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /maps/1
    # DELETE /maps/1.json
    def destroy
      @map = Map.find(params[:id])
      @map.destroy

      respond_to do |format|
        format.html { redirect_to maps_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /maps
  # GET /maps.json
  def index
    if (params[:conference_id])
      @maps = Conference.find(params[:conference_id]).maps
    else

    end
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render 'maps/index' }
    end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        if params[:conference_id]
         Conference.find(params[:conference_id]).maps << @map
        end

        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render json: @map, status: :created, location: @map }
      else
        format.html { render action: "new" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update
    @map = Map.find(params[:id])

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for @map , :html => {:multipart => true}  do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :map %>
  </div>
	<p>
	  <%= f.label :remote_map_url, "or image URL" %><br />
	  <%= f.text_field :remote_map_url %>
	</p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>map</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @maps.each do |map| %>
  <tr>
    <td><%= map.name %></td>
    <td><%= map.map %></td>
    <td><%= link_to 'Show', map %></td>
    <td><%= link_to 'Edit', edit_map_path(map) %></td>
    <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @map.name %>
</p>

<p>
  <b>Url:</b>
  <!%= image_tag @map.url_url(:thumb) %-->
  <%=  @map.map                               %>
</p>
                 <div> <%= image_tag @map.map %></div>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>