config/routes.rb
Iconference::Application.routes.draw do
  
  resources :maps

  root :to => 'static_pages#home'
  
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contact',    to: 'static_pages#contact',    via: 'get'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      resources :conferences do
        resources :sessions, :presentations, :authors, :speakers, :events, :maps
        resources :sessions do
          :presentations
        end
      end

      match '/authenticate', to: 'access#create'
    end
  end

  

  namespace :admin, defaults: {format: 'html'} do
    match '/dashboard', :to => 'dashboard#menu', via: 'get'
    resources :access, only: [:new, :create, :destroy]
    resources :institutions, :org_members, :attendees
    match '/signin',  to: 'access#new'
    match '/signout', to: 'access#destroy', via: 'delete'

    resources :conferences do
      resources :sessions, :authors, :speakers, :events,
                :attendees, :maps
      resources :sessions do
        :presentations
      end
      member do
        post 'import'
      end
    end
  end

  resources :users, :attendees, :authors, :events, :coffee_breaks,
  :events, :institutions, :keynotes,
  :org_members, :presentations, :rooms,
  :sessions, :speakers, :welcome_sessions, :workshops, :maps

  resources :schedules do
    collection do
      put 'add'
      delete 'remove'
    end
  end

  resources :conferences do
    get 'program', :on => :member
    resources :events, :sessions, :presentations, :authors, :speakers, :maps
    end

  resources :presentations do
    resources :authors, :speakers
  end

  resources :sessions do
    resources :presentations
  end

=begin
  resources :schedules do
    resources :sessions do
      get 'delete', :on => :collection
    end
  end
=end
  

  match ':controller/:id/:action'
  match ':controller/:id/:action/:presentation_id'
  match ':controller(/:action(/:id))(.:format)'

end

app/models/conference.rb
require 'socket'

class Conference < ActiveRecord::Base


  attr_accessible :avatar, :conf_date, :description, :local, :name, :hashtag, :remote_avatar_url


  has_many :attendees
  has_many :users, :through => :attendees
  has_many :sessions
  has_many :events
  has_and_belongs_to_many :org_members, :join_table => 'org_members_conferences'
  has_and_belongs_to_many :maps, :join_table => 'conferences_maps'


  mount_uploader :avatar, ConferenceAvatarUploader

  validates :local, :presence => true
  #if the picture will be stored in "assets", there's no need to verify format of URL.. GIF etc
  validates :conf_date, :presence => true
  validates :description, :presence => true
  validate :word_count_is_less_than_100
  validates :name, :presence => true , :uniqueness => true



  public

  def start_at
    conf_date
  end

  def avatar_url
    if Rails.env == 'development' && avatar != nil
      "http://localhost:3000#{avatar}"
    elsif Rails.env == 'production' && avatar != nil
        "http://193.136.122.140#{avatar}"
    else
      avatar
    end
  end

  def end_at
      dates = []
      self.sessions.each do |session|
        dates.append session.start_at.to_date
      end
      self.events.each do |event|
        dates.append event.end_at.to_date
      end
      dates.sort!.last


  end

  def import(file)

    f = File.open(file)
    doc = Nokogiri::XML(f)
    print doc
    parse_xml(doc)
  end

  private

  def word_count_is_less_than_100
    errors[:conference_description] << 'Too many words' if description.split.size > 99
  end

  def parse_xml(doc)
    doc.root.elements.each do |node|
      if node.node_name.eql? 'info'
        parse_info(node)
      end
    end
  end

  def parse_info(node)
    node.elements.each do |node|
      self.name = node.text.to_s if node.name.eql? 'name'
    end
  end

  def local_ip
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true  # turn off reverse DNS resolution temporarily

    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end

end

app/controllers/admin/conferences_controller.rb
module Admin
  class ConferencesController < ApplicationController

    def show
      @conference = Conference.find(params[:id])
      #render 'conferences/show'
    end

    # GET /conferences/1/edit
    def edit
      @conference = Conference.find(params[:id])
    end

    # PUT /conferences/1
    def update
      @conference = Conference.find(params[:id])
      if @conference.update_attributes(params[:conference])
        redirect_to @conference
        flash[:success] = 'Conference was successfully updated.'
      else
        render action: "edit"
      end
    end

    # GET /conferences/1/program
    def program
      @sessions = Session.find_all_by_conference_id(params[:id])
      @events = Conference.find(params[:id]).events
      respond_to do |format|
        format.html
        format.json { render 'conferences/program.json.jbuilder' }
      end
    end

    # GET /conferences/1/import
    def import
      begin
      @conference = Conference.find(params[:id])

      f = params[:file].open
      doc = Nokogiri::XML(f)
      root = doc.root

      #Info
      info = root.xpath('info')
      self.parse_info(info)

      sessions = root.xpath('sessions/session')
      print "\n"+'Number of sessions: '+sessions.count.to_s+"\n"

      @conference.sessions.delete_all
      sessions.each do |session|
        print "\nSession:\n"+session+"\n"
        self.parse_session(session)
      end

       @conference.save
        redirect_to admin_conference_url(@conference)
        flash[:success] = 'Conference imported successfully'


      rescue
        redirect_to admin_conference_url(@conference)
        flash[:error] = 'Unable to import conference'
      end
    end

    def parse_info(info)
      @conference.name = info.at_xpath('//name').text
      @conference.local = info.at_xpath('//local').text
      @conference.description = info.at_xpath('//description').text
      @conference.conf_date = Date.strptime(info.at_xpath('//date').text, '%d/%m/%Y')
    end

    def parse_session(session)
      new_session = Session.new
      print  "\n\n\n" + session.at_xpath('//name').text
      new_session.name = session.at_xpath('//name').text
      new_session.chair = session.at_xpath('//chair').text

      new_room = Room.new
      new_room.name = session.at_xpath('//room/name').text
      new_room.capacity = Integer(session.at_xpath('//room/capacity').text)
      new_room.save

      new_session.room_id = new_room.id

      new_session.conference_id = @conference.id

      new_session.save

      print 'session_id: '+new_session.id.to_s
      print 'session_conference:' + new_session.conference_id.to_s

      presentations = session.xpath('presentations/presentation')
      print "\n"+'Number of presentations: '+presentations.count.to_s+"\n"

      presentations.each do |presentation|
        print presentation
        self.parse_presentation(new_session, presentation)
      end
    end

    def parse_presentation(session, presentation)
      new_presentation = Presentation.new
      print "\n"+'Presentation title: '+presentation.at_xpath('//title').text+"\n"

      new_presentation.title = presentation.at_xpath('//title').text
      print "\n"+'Presentation start_at: '+DateTime.strptime(presentation.at_xpath('//start').text, '%d/%m/%Y %H:%M').to_s+"\n"
      new_presentation.start_at = DateTime.strptime(presentation.at_xpath('//start').text, '%d/%m/%Y %H:%M')
      new_presentation.end_at = DateTime.strptime(presentation.at_xpath('//end').text, '%d/%m/%Y %H:%M')
      new_presentation.article = presentation.at_xpath('//article').text

      # authors

      new_presentation.session_id = session.id
      new_presentation.save
    end



  end
end

app/controllers/api/v1/conferences_controller.rb
module Api
  module V1
    class ConferencesController < ApplicationController
      include RestrictAccess
      
      respond_to :json
      
      # GET /api/v1/conferences
      def index
        @conferences = Conference.all
        render :file => 'conferences/index.json.jbuilder'
      end
      
      # GET /api/v1/conferences/:id
      def show
        @conference = Conference.find(params[:id])
        render :file => 'conferences/show.json.jbuilder'
      end 
      
      # GET /api/v1/conferences/new
      def new
        respond_with Conference.create(params[:conference])
      end
      
      #edit
      
      #POST api/v1/conferences
      def create
        respond_with Conference.create(params[:conference])
      end
      
      # PUT api/v1/conferences/1
      def update
        respond_with Conference.update(params[:id], params[:conference])
      end
      
      # DELETE api/v1/conferences/1
      def destroy
        respond_with Conference.destroy(params[:id])
      end
      
    end
  end  
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
 
  #respond_with :html
 
  # GET /conferences
  def index
    @conferences = Conference.all
    # index.html.erb
  end

  # GET /conferences/1
  def show
    @conference = Conference.find(params[:id])
    # show.html.erb
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
    # new.html.erb
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  def create
    @conference = Conference.new(params[:conference])
    if @conference.save
      redirect_to @conference
      flash[:success] = 'Conference was successfully created.'
    else
      render action: "new"
      flash[:error] = 'An error occoured. Please try again later.'
    end
  end

  # PUT /conferences/1
  def update
    @conference = Conference.find(params[:id])
    if @conference.update_attributes(params[:conference])
      redirect_to @conference 
      flash[:success] = 'Conference was successfully updated.'
    else
      render action: "edit" 
    end
  end

  # DELETE /conferences/1
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy
    redirect_to conferences_url
  end

  # GET /conferences/1/program
  def program
    @sessions = Session.find_all_by_conference_id(params[:id])
    @events = Conference.find(params[:id]).events
    respond_to do |format|
      format.html
      format.json { render 'conferences/program.json.jbuilder' }
    end
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/admin/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </div>
	<p>
	  <%= f.file_field :avatar %>
	</p>
	<p>
	  <%= f.label :remote_avatar_url, "or image URL" %><br />
	  <%= f.text_field :remote_avatar_url %>
	</p>
  <div class="field">
    <%= f.label :conf_date %><br />
    <%= f.date_select :conf_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/admin/conferences/index.html.erb
<h1>Listing conferences</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Local</th>
    <th>Avatar</th>
    <th>Conf date</th>
    <th></th>
  </tr>

<% @conferences.each do |conference| %>
  <tr>
    <td><%= conference.name %></td>
    <td><%= conference.description %></td>
    <td><%= conference.local %></td>
    <td><%= conference.avatar %></td>
    <td><%= conference.conf_date %></td>
    <td>
	  <ul>
		<li><%= link_to 'Show', conference, class: 'option' %></li>
		<li><%= link_to 'Edit', edit_conference_path(conference), class: 'option' %></li>
		<li> <%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	  </ul>
	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conference', new_conference_path %>

app/views/admin/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/admin/conferences/show.html.erb
<conference>

  <info class="container">
	<div class="center hero-unit">
	  <h1><%= @conference.name %></h1>

	  <div id="firstcolumn" class="column">
		<avatar><!%= image_tag @conference.avatar.to_s.va %></avatar>
		<p><span class=label>Description</span><%= @conference.description %></p>
	  </div>
	  <div id="secondcolumn" class="column">

		<p><span class=label>Local</span><%= @conference.local %></p>

		<p><span class=label>Start at</span><%= @conference.start_at %></p>
		<p><span class=label>End at</span><%= @conference.end_at %></p>

	  </div>
	  <%= link_to 'Edit', edit_admin_conference_path(@conference), :class => 'options' %>
	</div>
  </info>

  <manage class="container">
  <div class="center hero-unit">
	<h2>Manage</h2>
	<div><%= link_to 'Attendees', admin_conference_attendees_url(@conference) %></div>
	<div><%= link_to 'Sessions' , admin_conference_sessions_url(@conference) %></div>
	<div><%= link_to 'Events' , admin_conference_events_url(@conference) %></div>
	<div><%= link_to 'Maps' , admin_conference_maps_url(@conference) %></div>
  </div>
</manage>

  <manage class="container">
	<div class="hero-unit">
	  <h2>Import</h2>
	  <import>
		<%= form_tag import_admin_conference_url(@conference),  multipart: true do %>
			<%= file_field_tag :file %>
			<%= submit_tag 'Import' %>
		<% end %>
	  </import>
	</div>
  </manage>
</conference>