config/routes.rb
Iconference::Application.routes.draw do
  
  resources :maps

  root :to => 'static_pages#home'
  
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contact',    to: 'static_pages#contact',    via: 'get'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      resources :conferences do
        resources :sessions, :presentations, :authors, :speakers, :events, :maps
        resources :sessions do
          :presentations
        end
      end

      match '/authenticate', to: 'access#create'
    end
  end

  

  namespace :admin, defaults: {format: 'html'} do
    match '/dashboard', :to => 'dashboard#menu', via: 'get'
    resources :access, only: [:new, :create, :destroy]
    resources :institutions, :org_members, :attendees
    match '/signin',  to: 'access#new'
    match '/signout', to: 'access#destroy', via: 'delete'

    resources :conferences do
      resources :sessions, :authors, :speakers, :events,
                :attendees, :maps
      resources :sessions do
        :presentations
      end
      member do
        post 'import'
      end
    end
  end

  resources :users, :attendees, :authors, :events, :coffee_breaks,
  :events, :institutions, :keynotes,
  :org_members, :presentations, :rooms,
  :sessions, :speakers, :welcome_sessions, :workshops, :maps

  resources :schedules do
    collection do
      put 'add'
      delete 'remove'
    end
  end

  resources :conferences do
    get 'program', :on => :member
    resources :events, :sessions, :presentations, :authors, :speakers, :maps
    end

  resources :presentations do
    resources :authors, :speakers
  end

  resources :sessions do
    resources :presentations
  end

=begin
  resources :schedules do
    resources :sessions do
      get 'delete', :on => :collection
    end
  end
=end
  

  match ':controller/:id/:action'
  match ':controller/:id/:action/:presentation_id'
  match ':controller(/:action(/:id))(.:format)'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :checkin, :conference_id, :favorites, :log, :schedule_id, :user_id

  serialize :favorites,Array
  serialize :log,Array

  #Associations

  belongs_to :user
  belongs_to :conference
  has_many :rates
  has_many :requests
  has_many :presentations, :through => :rates
  has_many :notifications
  belongs_to :schedule

  # VALIDATIONS
  #validates_presence_of :conference

  validates :checkin, :presence => true#, :inclusion => { :in => [true, false],:message => "%{value} is not a valid checkin" }


  after_create :check_for_existing_users

  #verifica caso quando se crie um attendee, não se especifique o user_id visto não existir
  #é criado um utilizador e passado o seu ID para o user_id do Attendee
  def check_for_existing_users
    if self.user_id.blank?
      Attendee.find(self.id).update_attribute(:user_id,User.count+1)
      User.create()
    end
  end
end

app/controllers/admin/attendees_controller.rb
module Admin
  class AttendeesController < ApplicationController
    # GET /attendees
    # GET /attendees.json
    def index
      @conference = Conference.find(params[:conference_id])
      @attendees = @conference.attendees
    end

    # GET /attendees/1
    # GET /attendees/1.json
    def show
      @attendee = Attendee.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @attendee }
      end
    end

    # GET /attendees/new
    # GET /attendees/new.json
    def new
      @attendee = Attendee.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @attendee }
      end
    end

    # GET /attendees/1/edit
    def edit
      @attendee = Attendee.find(params[:id])
    end

    # POST /attendees
    # POST /attendees.json
    def create
      @attendee = Attendee.new(params[:attendee])

      respond_to do |format|
        if @attendee.save
          format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
          format.json { render json: @attendee, status: :created, location: @attendee }
        else
          format.html { render action: "new" }
          format.json { render json: @attendee.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /attendees/1
    # PUT /attendees/1.json
    def update
      @attendee = Attendee.find(params[:id])

      respond_to do |format|
        if @attendee.update_attributes(params[:attendee])
          format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @attendee.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /attendees/1
    # DELETE /attendees/1.json
    def destroy
      @attendee = Attendee.find(params[:id])
      @attendee.destroy

      respond_to do |format|
        format.html { redirect_to attendees_url }
        format.json { head :no_content }
      end
    end


    def notifications
      @notification = Notification.find_all_by_attendee_id(params[:id])

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @notification }
      end
    end

    def presentations
      @attendee =Attendee.find(params[:id])
      @schedule = Schedule.find(@attendee.schedule_id)

      @schedule1=@schedule.presentations

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @schedule1 }
      end
    end

  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendees }
    end
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/new
  # GET /attendees/new.json
  def new
    @attendee = Attendee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/1/edit
  def edit
    @attendee = Attendee.find(params[:id])
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(params[:attendee])

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render json: @attendee, status: :created, location: @attendee }
      else
        format.html { render action: "new" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendees/1
  # PUT /attendees/1.json
  def update
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      if @attendee.update_attributes(params[:attendee])
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to attendees_url }
      format.json { head :no_content }
    end
  end


  def notifications
    @notification = Notification.find_all_by_attendee_id(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  def presentations
    @attendee =Attendee.find(params[:id])
    @schedule = Schedule.find(@attendee.schedule_id)

    @schedule1=@schedule.presentations

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule1 }
    end
  end

  def putPres
    @attendee =Attendee.find(params[:id])
    @schedule = Schedule.find(@attendee.schedule_id)
    @pres=Presentation.find(params[:presentation_id])

    @presentation=@schedule.presentations << @pres
    @schedPres=@schedule.presentations

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedPres}
    end

  end

  def deletePres
    @attendee =Attendee.find(params[:id])
    @schedule = Schedule.find(@attendee.schedule_id)
    @pres=Presentation.find(params[:presentation_id])

    @presentation=@schedule.presentations.delete(@pres)

    @schedPres=@schedule.presentations

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedPres}
    end

  end

end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/admin/attendees/_form.html.erb
<%= form_for(@attendee) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :conference_id %><br />
    <%= f.number_field :conference_id %>
  </div>
  <div class="field">
    <%= f.label :schedule_id %><br />
    <%= f.number_field :schedule_id %>
  </div>
  <div class="field">
    <%= f.label :checkin %><br />
    <%= f.check_box :checkin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/admin/attendees/index.html.erb
<h1>Listing attendees</h1>

<table>
  <tr>
    <th>User</th>
	<th>Email</th>
    <th>Checkin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendees.each do |attendee| %>
  <tr>
    <td><%= attendee.user.name %></td>
	<td><%= attendee.user.email %></td>
    <td><%= attendee.checkin %></td>
    <td><%= link_to 'Show', attendee %></td>
    <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
    <td><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendee', new_attendee_path %>

app/views/admin/attendees/new.html.erb
<h1>New attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

app/views/admin/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @attendee.user_id %>
</p>

<p>
  <b>Conference:</b>
  <%= @attendee.conference_id %>
</p>

<p>
  <b>Schedule:</b>
  <%= @attendee.schedule_id %>
</p>

<p>
  <b>Checkin:</b>
  <%= @attendee.checkin %>
</p>

<p>
  <b>Log:</b>
  <%= @attendee.log %>
</p>

<p>
  <b>Favorites:</b>
  <%= @attendee.favorites %>
</p>


<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>